// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/mcp/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/server/mcp/handler.go -destination=internal/server/mcp/mock_svc_test.go -package=mcp
//

// Package mcp is a generated GoMock package.
package mcp

import (
	context "context"
	reflect "reflect"

	service "github.com/mmadfox/swag2mcp/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSvc is a mock of Svc interface.
type MockSvc struct {
	ctrl     *gomock.Controller
	recorder *MockSvcMockRecorder
	isgomock struct{}
}

// MockSvcMockRecorder is the mock recorder for MockSvc.
type MockSvcMockRecorder struct {
	mock *MockSvc
}

// NewMockSvc creates a new mock instance.
func NewMockSvc(ctrl *gomock.Controller) *MockSvc {
	mock := &MockSvc{ctrl: ctrl}
	mock.recorder = &MockSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSvc) EXPECT() *MockSvcMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockSvc) Auth(arg0 context.Context, req service.AuthRequest) (service.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", arg0, req)
	ret0, _ := ret[0].(service.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockSvcMockRecorder) Auth(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockSvc)(nil).Auth), arg0, req)
}

// CollectionByID mocks base method.
func (m *MockSvc) CollectionByID(arg0 context.Context, req service.CollectionByIDRequest) (service.CollectionByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionByID", arg0, req)
	ret0, _ := ret[0].(service.CollectionByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionByID indicates an expected call of CollectionByID.
func (mr *MockSvcMockRecorder) CollectionByID(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionByID", reflect.TypeOf((*MockSvc)(nil).CollectionByID), arg0, req)
}

// CollectionsBySpec mocks base method.
func (m *MockSvc) CollectionsBySpec(arg0 context.Context, req service.CollectionsRequest) (service.CollectionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionsBySpec", arg0, req)
	ret0, _ := ret[0].(service.CollectionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionsBySpec indicates an expected call of CollectionsBySpec.
func (mr *MockSvcMockRecorder) CollectionsBySpec(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionsBySpec", reflect.TypeOf((*MockSvc)(nil).CollectionsBySpec), arg0, req)
}

// EndpointByID mocks base method.
func (m *MockSvc) EndpointByID(arg0 context.Context, req service.EndpointByIDRequest) (service.EndpointByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointByID", arg0, req)
	ret0, _ := ret[0].(service.EndpointByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointByID indicates an expected call of EndpointByID.
func (mr *MockSvcMockRecorder) EndpointByID(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointByID", reflect.TypeOf((*MockSvc)(nil).EndpointByID), arg0, req)
}

// EndpointsByCollection mocks base method.
func (m *MockSvc) EndpointsByCollection(arg0 context.Context, req service.EndpointsByCollectionRequest) (service.EndpointsByCollectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointsByCollection", arg0, req)
	ret0, _ := ret[0].(service.EndpointsByCollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointsByCollection indicates an expected call of EndpointsByCollection.
func (mr *MockSvcMockRecorder) EndpointsByCollection(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointsByCollection", reflect.TypeOf((*MockSvc)(nil).EndpointsByCollection), arg0, req)
}

// EndpointsBySpec mocks base method.
func (m *MockSvc) EndpointsBySpec(arg0 context.Context, req service.EndpointsBySpecRequest) (service.EndpointsBySpecResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointsBySpec", arg0, req)
	ret0, _ := ret[0].(service.EndpointsBySpecResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointsBySpec indicates an expected call of EndpointsBySpec.
func (mr *MockSvcMockRecorder) EndpointsBySpec(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointsBySpec", reflect.TypeOf((*MockSvc)(nil).EndpointsBySpec), arg0, req)
}

// EndpointsByTag mocks base method.
func (m *MockSvc) EndpointsByTag(arg0 context.Context, req service.EndpointsByTagRequest) (service.EndpointsByTagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointsByTag", arg0, req)
	ret0, _ := ret[0].(service.EndpointsByTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointsByTag indicates an expected call of EndpointsByTag.
func (mr *MockSvcMockRecorder) EndpointsByTag(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointsByTag", reflect.TypeOf((*MockSvc)(nil).EndpointsByTag), arg0, req)
}

// Info mocks base method.
func (m *MockSvc) Info(arg0 context.Context) (service.InfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", arg0)
	ret0, _ := ret[0].(service.InfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockSvcMockRecorder) Info(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockSvc)(nil).Info), arg0)
}

// Inspect mocks base method.
func (m *MockSvc) Inspect(arg0 context.Context, req service.InspectRequest) (service.InspectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", arg0, req)
	ret0, _ := ret[0].(service.InspectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockSvcMockRecorder) Inspect(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockSvc)(nil).Inspect), arg0, req)
}

// Invoke mocks base method.
func (m *MockSvc) Invoke(arg0 context.Context, req service.InvokeRequest) (service.InvokeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", arg0, req)
	ret0, _ := ret[0].(service.InvokeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockSvcMockRecorder) Invoke(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockSvc)(nil).Invoke), arg0, req)
}

// MakeToolDefinitions mocks base method.
func (m *MockSvc) MakeToolDefinitions() (service.ToolDefinitions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeToolDefinitions")
	ret0, _ := ret[0].(service.ToolDefinitions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeToolDefinitions indicates an expected call of MakeToolDefinitions.
func (mr *MockSvcMockRecorder) MakeToolDefinitions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeToolDefinitions", reflect.TypeOf((*MockSvc)(nil).MakeToolDefinitions))
}

// Search mocks base method.
func (m *MockSvc) Search(ctx context.Context, req service.SearchRequest) (service.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].(service.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSvcMockRecorder) Search(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSvc)(nil).Search), ctx, req)
}

// SpecByID mocks base method.
func (m *MockSvc) SpecByID(arg0 context.Context, req service.SpecByIDRequest) (service.SpecByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpecByID", arg0, req)
	ret0, _ := ret[0].(service.SpecByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpecByID indicates an expected call of SpecByID.
func (mr *MockSvcMockRecorder) SpecByID(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpecByID", reflect.TypeOf((*MockSvc)(nil).SpecByID), arg0, req)
}

// Specs mocks base method.
func (m *MockSvc) Specs(arg0 context.Context) (service.SpecsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Specs", arg0)
	ret0, _ := ret[0].(service.SpecsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Specs indicates an expected call of Specs.
func (mr *MockSvcMockRecorder) Specs(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Specs", reflect.TypeOf((*MockSvc)(nil).Specs), arg0)
}

// TagByID mocks base method.
func (m *MockSvc) TagByID(arg0 context.Context, req service.TagByIDRequest) (service.TagByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagByID", arg0, req)
	ret0, _ := ret[0].(service.TagByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagByID indicates an expected call of TagByID.
func (mr *MockSvcMockRecorder) TagByID(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagByID", reflect.TypeOf((*MockSvc)(nil).TagByID), arg0, req)
}

// TagsByCollection mocks base method.
func (m *MockSvc) TagsByCollection(arg0 context.Context, req service.TagsByCollectionRequest) (service.TagsByCollectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagsByCollection", arg0, req)
	ret0, _ := ret[0].(service.TagsByCollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagsByCollection indicates an expected call of TagsByCollection.
func (mr *MockSvcMockRecorder) TagsByCollection(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsByCollection", reflect.TypeOf((*MockSvc)(nil).TagsByCollection), arg0, req)
}

// TagsBySpec mocks base method.
func (m *MockSvc) TagsBySpec(arg0 context.Context, req service.TagsBySpecRequest) (service.TagsBySpecResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagsBySpec", arg0, req)
	ret0, _ := ret[0].(service.TagsBySpecResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagsBySpec indicates an expected call of TagsBySpec.
func (mr *MockSvcMockRecorder) TagsBySpec(arg0, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsBySpec", reflect.TypeOf((*MockSvc)(nil).TagsBySpec), arg0, req)
}
