version: 2

project_name: swag2mcp

before:
  hooks:
    - go mod tidy

builds:
  - id: swag2mcp
    main: ./cmd/swag2mcp
    binary: swag2mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mmadfox/swag2mcp/internal/commands.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: swag2mcp-mock
    main: ./cmd/swag2mcp-mock
    binary: swag2mcp-mock
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mmadfox/swag2mcp/internal/commands.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: swag2mcp
    builds: [swag2mcp]
    formats: [tar.gz]
    name_template: >-
      swag2mcp_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: swag2mcp-mock
    builds: [swag2mcp-mock]
    formats: [tar.gz]
    name_template: >-
      swag2mcp-mock_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: swag2mcp
    package_name: swag2mcp
    builds: [swag2mcp]
    vendor: mmadfox
    homepage: https://github.com/mmadfox/swag2mcp
    maintainer: mmadfox
    description: Bridge OpenAPI/Swagger/Postman specs with LLM agents via MCP
    formats:
      - deb
      - rpm

dockers:
  - id: swag2mcp
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/mmadfox/swag2mcp:{{ .Version }}"
      - "ghcr.io/mmadfox/swag2mcp:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"

brews:
  - name: swag2mcp
    ids: [swag2mcp]
    repository:
      owner: mmadfox
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@mmadfox.dev
    homepage: https://github.com/mmadfox/swag2mcp
    description: Bridge OpenAPI/Swagger/Postman specs with LLM agents via MCP
    license: MIT

scoops:
  - name: swag2mcp
    ids: [swag2mcp]
    repository:
      owner: mmadfox
      name: scoop-bucket
    commit_author:
      name: goreleaserbot
      email: bot@mmadfox.dev
    homepage: https://github.com/mmadfox/swag2mcp
    description: Bridge OpenAPI/Swagger/Postman specs with LLM agents via MCP
    license: MIT

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "README"
