version: 2

project_name: swag2mcp

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/swag2mcp
    binary: swag2mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mmadfox/swag2mcp/internal/commands.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "README"
