FROM alpine:latest
RUN apk add --no-cache su-exec && \
    adduser -D -u 65532 -h /home/nonroot nonroot
ENV HOME=/home/nonroot
COPY swag2mcp-mock /usr/local/bin/swag2mcp-mock
COPY scripts/entrypoint-mock.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
