# swag2mcp — Multiple Collections
specs:
  - domain: crm-api
    base_url: https://api.crm.example.com
    llm_title: CRM API
    collections:
      - llm_title: Contacts
        location: https://raw.githubusercontent.com/mmadfox/swag2mcp/main/specs/meteo.json
      - llm_title: Deals
        location: https://raw.githubusercontent.com/mmadfox/swag2mcp/main/specs/meteo.json
      - llm_title: Tasks
        location: https://raw.githubusercontent.com/mmadfox/swag2mcp/main/specs/meteo.json
      - llm_title: Reports
        location: https://raw.githubusercontent.com/mmadfox/swag2mcp/main/specs/meteo.json
