// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/deps.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/deps.go -destination=internal/service/mock_deps_test.go -package=service -typed
//
// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	config "github.com/mmadfox/swag2mcp/internal/config"
	httpclient "github.com/mmadfox/swag2mcp/internal/httpclient"
	model "github.com/mmadfox/swag2mcp/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexReader is a mock of IndexReader interface.
type MockIndexReader struct {
	ctrl     *gomock.Controller
	recorder *MockIndexReaderMockRecorder
	isgomock struct{}
}

// MockIndexReaderMockRecorder is the mock recorder for MockIndexReader.
type MockIndexReaderMockRecorder struct {
	mock *MockIndexReader
}

// NewMockIndexReader creates a new mock instance.
func NewMockIndexReader(ctrl *gomock.Controller) *MockIndexReader {
	mock := &MockIndexReader{ctrl: ctrl}
	mock.recorder = &MockIndexReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexReader) EXPECT() *MockIndexReaderMockRecorder {
	return m.recorder
}

// AllSpecs mocks base method.
func (m *MockIndexReader) AllSpecs() []*model.Spec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllSpecs")
	ret0, _ := ret[0].([]*model.Spec)
	return ret0
}

// AllSpecs indicates an expected call of AllSpecs.
func (mr *MockIndexReaderMockRecorder) AllSpecs() *MockIndexReaderAllSpecsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllSpecs", reflect.TypeOf((*MockIndexReader)(nil).AllSpecs))
	return &MockIndexReaderAllSpecsCall{Call: call}
}

// MockIndexReaderAllSpecsCall wrap *gomock.Call
type MockIndexReaderAllSpecsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderAllSpecsCall) Return(arg0 []*model.Spec) *MockIndexReaderAllSpecsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderAllSpecsCall) Do(f func() []*model.Spec) *MockIndexReaderAllSpecsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderAllSpecsCall) DoAndReturn(f func() []*model.Spec) *MockIndexReaderAllSpecsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CollectionByID mocks base method.
func (m *MockIndexReader) CollectionByID(id string) (*model.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionByID", id)
	ret0, _ := ret[0].(*model.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionByID indicates an expected call of CollectionByID.
func (mr *MockIndexReaderMockRecorder) CollectionByID(id any) *MockIndexReaderCollectionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionByID", reflect.TypeOf((*MockIndexReader)(nil).CollectionByID), id)
	return &MockIndexReaderCollectionByIDCall{Call: call}
}

// MockIndexReaderCollectionByIDCall wrap *gomock.Call
type MockIndexReaderCollectionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderCollectionByIDCall) Return(arg0 *model.Collection, arg1 error) *MockIndexReaderCollectionByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderCollectionByIDCall) Do(f func(string) (*model.Collection, error)) *MockIndexReaderCollectionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderCollectionByIDCall) DoAndReturn(f func(string) (*model.Collection, error)) *MockIndexReaderCollectionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CollectionsBySpec mocks base method.
func (m *MockIndexReader) CollectionsBySpec(specID string) ([]*model.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionsBySpec", specID)
	ret0, _ := ret[0].([]*model.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionsBySpec indicates an expected call of CollectionsBySpec.
func (mr *MockIndexReaderMockRecorder) CollectionsBySpec(specID any) *MockIndexReaderCollectionsBySpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionsBySpec", reflect.TypeOf((*MockIndexReader)(nil).CollectionsBySpec), specID)
	return &MockIndexReaderCollectionsBySpecCall{Call: call}
}

// MockIndexReaderCollectionsBySpecCall wrap *gomock.Call
type MockIndexReaderCollectionsBySpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderCollectionsBySpecCall) Return(arg0 []*model.Collection, arg1 error) *MockIndexReaderCollectionsBySpecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderCollectionsBySpecCall) Do(f func(string) ([]*model.Collection, error)) *MockIndexReaderCollectionsBySpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderCollectionsBySpecCall) DoAndReturn(f func(string) ([]*model.Collection, error)) *MockIndexReaderCollectionsBySpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EndpointByCollection mocks base method.
func (m *MockIndexReader) EndpointByCollection(collectionID string) ([]*model.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointByCollection", collectionID)
	ret0, _ := ret[0].([]*model.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointByCollection indicates an expected call of EndpointByCollection.
func (mr *MockIndexReaderMockRecorder) EndpointByCollection(collectionID any) *MockIndexReaderEndpointByCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointByCollection", reflect.TypeOf((*MockIndexReader)(nil).EndpointByCollection), collectionID)
	return &MockIndexReaderEndpointByCollectionCall{Call: call}
}

// MockIndexReaderEndpointByCollectionCall wrap *gomock.Call
type MockIndexReaderEndpointByCollectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderEndpointByCollectionCall) Return(arg0 []*model.Endpoint, arg1 error) *MockIndexReaderEndpointByCollectionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderEndpointByCollectionCall) Do(f func(string) ([]*model.Endpoint, error)) *MockIndexReaderEndpointByCollectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderEndpointByCollectionCall) DoAndReturn(f func(string) ([]*model.Endpoint, error)) *MockIndexReaderEndpointByCollectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EndpointByID mocks base method.
func (m *MockIndexReader) EndpointByID(id string) (*model.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointByID", id)
	ret0, _ := ret[0].(*model.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointByID indicates an expected call of EndpointByID.
func (mr *MockIndexReaderMockRecorder) EndpointByID(id any) *MockIndexReaderEndpointByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointByID", reflect.TypeOf((*MockIndexReader)(nil).EndpointByID), id)
	return &MockIndexReaderEndpointByIDCall{Call: call}
}

// MockIndexReaderEndpointByIDCall wrap *gomock.Call
type MockIndexReaderEndpointByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderEndpointByIDCall) Return(arg0 *model.Endpoint, arg1 error) *MockIndexReaderEndpointByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderEndpointByIDCall) Do(f func(string) (*model.Endpoint, error)) *MockIndexReaderEndpointByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderEndpointByIDCall) DoAndReturn(f func(string) (*model.Endpoint, error)) *MockIndexReaderEndpointByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EndpointsBySpec mocks base method.
func (m *MockIndexReader) EndpointsBySpec(specID string) ([]*model.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointsBySpec", specID)
	ret0, _ := ret[0].([]*model.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointsBySpec indicates an expected call of EndpointsBySpec.
func (mr *MockIndexReaderMockRecorder) EndpointsBySpec(specID any) *MockIndexReaderEndpointsBySpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointsBySpec", reflect.TypeOf((*MockIndexReader)(nil).EndpointsBySpec), specID)
	return &MockIndexReaderEndpointsBySpecCall{Call: call}
}

// MockIndexReaderEndpointsBySpecCall wrap *gomock.Call
type MockIndexReaderEndpointsBySpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderEndpointsBySpecCall) Return(arg0 []*model.Endpoint, arg1 error) *MockIndexReaderEndpointsBySpecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderEndpointsBySpecCall) Do(f func(string) ([]*model.Endpoint, error)) *MockIndexReaderEndpointsBySpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderEndpointsBySpecCall) DoAndReturn(f func(string) ([]*model.Endpoint, error)) *MockIndexReaderEndpointsBySpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EndpointsByTag mocks base method.
func (m *MockIndexReader) EndpointsByTag(tagID string) ([]*model.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointsByTag", tagID)
	ret0, _ := ret[0].([]*model.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndpointsByTag indicates an expected call of EndpointsByTag.
func (mr *MockIndexReaderMockRecorder) EndpointsByTag(tagID any) *MockIndexReaderEndpointsByTagCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointsByTag", reflect.TypeOf((*MockIndexReader)(nil).EndpointsByTag), tagID)
	return &MockIndexReaderEndpointsByTagCall{Call: call}
}

// MockIndexReaderEndpointsByTagCall wrap *gomock.Call
type MockIndexReaderEndpointsByTagCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderEndpointsByTagCall) Return(arg0 []*model.Endpoint, arg1 error) *MockIndexReaderEndpointsByTagCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderEndpointsByTagCall) Do(f func(string) ([]*model.Endpoint, error)) *MockIndexReaderEndpointsByTagCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderEndpointsByTagCall) DoAndReturn(f func(string) ([]*model.Endpoint, error)) *MockIndexReaderEndpointsByTagCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Search mocks base method.
func (m *MockIndexReader) Search(ctx context.Context, query string, limit int) ([]*model.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit)
	ret0, _ := ret[0].([]*model.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIndexReaderMockRecorder) Search(ctx, query, limit any) *MockIndexReaderSearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIndexReader)(nil).Search), ctx, query, limit)
	return &MockIndexReaderSearchCall{Call: call}
}

// MockIndexReaderSearchCall wrap *gomock.Call
type MockIndexReaderSearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderSearchCall) Return(arg0 []*model.Endpoint, arg1 error) *MockIndexReaderSearchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderSearchCall) Do(f func(context.Context, string, int) ([]*model.Endpoint, error)) *MockIndexReaderSearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderSearchCall) DoAndReturn(f func(context.Context, string, int) ([]*model.Endpoint, error)) *MockIndexReaderSearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SpecByID mocks base method.
func (m *MockIndexReader) SpecByID(id string) (*model.Spec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpecByID", id)
	ret0, _ := ret[0].(*model.Spec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpecByID indicates an expected call of SpecByID.
func (mr *MockIndexReaderMockRecorder) SpecByID(id any) *MockIndexReaderSpecByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpecByID", reflect.TypeOf((*MockIndexReader)(nil).SpecByID), id)
	return &MockIndexReaderSpecByIDCall{Call: call}
}

// MockIndexReaderSpecByIDCall wrap *gomock.Call
type MockIndexReaderSpecByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderSpecByIDCall) Return(arg0 *model.Spec, arg1 error) *MockIndexReaderSpecByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderSpecByIDCall) Do(f func(string) (*model.Spec, error)) *MockIndexReaderSpecByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderSpecByIDCall) DoAndReturn(f func(string) (*model.Spec, error)) *MockIndexReaderSpecByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TagByID mocks base method.
func (m *MockIndexReader) TagByID(id string) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagByID", id)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagByID indicates an expected call of TagByID.
func (mr *MockIndexReaderMockRecorder) TagByID(id any) *MockIndexReaderTagByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagByID", reflect.TypeOf((*MockIndexReader)(nil).TagByID), id)
	return &MockIndexReaderTagByIDCall{Call: call}
}

// MockIndexReaderTagByIDCall wrap *gomock.Call
type MockIndexReaderTagByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderTagByIDCall) Return(arg0 *model.Tag, arg1 error) *MockIndexReaderTagByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderTagByIDCall) Do(f func(string) (*model.Tag, error)) *MockIndexReaderTagByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderTagByIDCall) DoAndReturn(f func(string) (*model.Tag, error)) *MockIndexReaderTagByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TagsByCollection mocks base method.
func (m *MockIndexReader) TagsByCollection(collectionID string) ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagsByCollection", collectionID)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagsByCollection indicates an expected call of TagsByCollection.
func (mr *MockIndexReaderMockRecorder) TagsByCollection(collectionID any) *MockIndexReaderTagsByCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsByCollection", reflect.TypeOf((*MockIndexReader)(nil).TagsByCollection), collectionID)
	return &MockIndexReaderTagsByCollectionCall{Call: call}
}

// MockIndexReaderTagsByCollectionCall wrap *gomock.Call
type MockIndexReaderTagsByCollectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderTagsByCollectionCall) Return(arg0 []*model.Tag, arg1 error) *MockIndexReaderTagsByCollectionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderTagsByCollectionCall) Do(f func(string) ([]*model.Tag, error)) *MockIndexReaderTagsByCollectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderTagsByCollectionCall) DoAndReturn(f func(string) ([]*model.Tag, error)) *MockIndexReaderTagsByCollectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TagsBySpec mocks base method.
func (m *MockIndexReader) TagsBySpec(specID string) ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagsBySpec", specID)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagsBySpec indicates an expected call of TagsBySpec.
func (mr *MockIndexReaderMockRecorder) TagsBySpec(specID any) *MockIndexReaderTagsBySpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsBySpec", reflect.TypeOf((*MockIndexReader)(nil).TagsBySpec), specID)
	return &MockIndexReaderTagsBySpecCall{Call: call}
}

// MockIndexReaderTagsBySpecCall wrap *gomock.Call
type MockIndexReaderTagsBySpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexReaderTagsBySpecCall) Return(arg0 []*model.Tag, arg1 error) *MockIndexReaderTagsBySpecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexReaderTagsBySpecCall) Do(f func(string) ([]*model.Tag, error)) *MockIndexReaderTagsBySpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexReaderTagsBySpecCall) DoAndReturn(f func(string) ([]*model.Tag, error)) *MockIndexReaderTagsBySpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWorkspaceOps is a mock of WorkspaceOps interface.
type MockWorkspaceOps struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceOpsMockRecorder
	isgomock struct{}
}

// MockWorkspaceOpsMockRecorder is the mock recorder for MockWorkspaceOps.
type MockWorkspaceOpsMockRecorder struct {
	mock *MockWorkspaceOps
}

// NewMockWorkspaceOps creates a new mock instance.
func NewMockWorkspaceOps(ctrl *gomock.Controller) *MockWorkspaceOps {
	mock := &MockWorkspaceOps{ctrl: ctrl}
	mock.recorder = &MockWorkspaceOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceOps) EXPECT() *MockWorkspaceOpsMockRecorder {
	return m.recorder
}

// ConfigNotExists mocks base method.
func (m *MockWorkspaceOps) ConfigNotExists() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigNotExists")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ConfigNotExists indicates an expected call of ConfigNotExists.
func (mr *MockWorkspaceOpsMockRecorder) ConfigNotExists() *MockWorkspaceOpsConfigNotExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigNotExists", reflect.TypeOf((*MockWorkspaceOps)(nil).ConfigNotExists))
	return &MockWorkspaceOpsConfigNotExistsCall{Call: call}
}

// MockWorkspaceOpsConfigNotExistsCall wrap *gomock.Call
type MockWorkspaceOpsConfigNotExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsConfigNotExistsCall) Return(arg0 bool) *MockWorkspaceOpsConfigNotExistsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsConfigNotExistsCall) Do(f func() bool) *MockWorkspaceOpsConfigNotExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsConfigNotExistsCall) DoAndReturn(f func() bool) *MockWorkspaceOpsConfigNotExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfigPath mocks base method.
func (m *MockWorkspaceOps) ConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// ConfigPath indicates an expected call of ConfigPath.
func (mr *MockWorkspaceOpsMockRecorder) ConfigPath() *MockWorkspaceOpsConfigPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigPath", reflect.TypeOf((*MockWorkspaceOps)(nil).ConfigPath))
	return &MockWorkspaceOpsConfigPathCall{Call: call}
}

// MockWorkspaceOpsConfigPathCall wrap *gomock.Call
type MockWorkspaceOpsConfigPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsConfigPathCall) Return(arg0 string) *MockWorkspaceOpsConfigPathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsConfigPathCall) Do(f func() string) *MockWorkspaceOpsConfigPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsConfigPathCall) DoAndReturn(f func() string) *MockWorkspaceOpsConfigPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyAuthScriptsToExport mocks base method.
func (m *MockWorkspaceOps) CopyAuthScriptsToExport(dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyAuthScriptsToExport", dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyAuthScriptsToExport indicates an expected call of CopyAuthScriptsToExport.
func (mr *MockWorkspaceOpsMockRecorder) CopyAuthScriptsToExport(dst any) *MockWorkspaceOpsCopyAuthScriptsToExportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyAuthScriptsToExport", reflect.TypeOf((*MockWorkspaceOps)(nil).CopyAuthScriptsToExport), dst)
	return &MockWorkspaceOpsCopyAuthScriptsToExportCall{Call: call}
}

// MockWorkspaceOpsCopyAuthScriptsToExportCall wrap *gomock.Call
type MockWorkspaceOpsCopyAuthScriptsToExportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsCopyAuthScriptsToExportCall) Return(arg0 error) *MockWorkspaceOpsCopyAuthScriptsToExportCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsCopyAuthScriptsToExportCall) Do(f func(string) error) *MockWorkspaceOpsCopyAuthScriptsToExportCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsCopyAuthScriptsToExportCall) DoAndReturn(f func(string) error) *MockWorkspaceOpsCopyAuthScriptsToExportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyAuthScriptsToWorkspace mocks base method.
func (m *MockWorkspaceOps) CopyAuthScriptsToWorkspace(src string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyAuthScriptsToWorkspace", src)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyAuthScriptsToWorkspace indicates an expected call of CopyAuthScriptsToWorkspace.
func (mr *MockWorkspaceOpsMockRecorder) CopyAuthScriptsToWorkspace(src any) *MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyAuthScriptsToWorkspace", reflect.TypeOf((*MockWorkspaceOps)(nil).CopyAuthScriptsToWorkspace), src)
	return &MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall{Call: call}
}

// MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall wrap *gomock.Call
type MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall) Return(arg0 error) *MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall) Do(f func(string) error) *MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall) DoAndReturn(f func(string) error) *MockWorkspaceOpsCopyAuthScriptsToWorkspaceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopySpecsToWorkspace mocks base method.
func (m *MockWorkspaceOps) CopySpecsToWorkspace(src string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopySpecsToWorkspace", src)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopySpecsToWorkspace indicates an expected call of CopySpecsToWorkspace.
func (mr *MockWorkspaceOpsMockRecorder) CopySpecsToWorkspace(src any) *MockWorkspaceOpsCopySpecsToWorkspaceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopySpecsToWorkspace", reflect.TypeOf((*MockWorkspaceOps)(nil).CopySpecsToWorkspace), src)
	return &MockWorkspaceOpsCopySpecsToWorkspaceCall{Call: call}
}

// MockWorkspaceOpsCopySpecsToWorkspaceCall wrap *gomock.Call
type MockWorkspaceOpsCopySpecsToWorkspaceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsCopySpecsToWorkspaceCall) Return(arg0 error) *MockWorkspaceOpsCopySpecsToWorkspaceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsCopySpecsToWorkspaceCall) Do(f func(string) error) *MockWorkspaceOpsCopySpecsToWorkspaceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsCopySpecsToWorkspaceCall) DoAndReturn(f func(string) error) *MockWorkspaceOpsCopySpecsToWorkspaceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateExportDir mocks base method.
func (m *MockWorkspaceOps) CreateExportDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExportDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExportDir indicates an expected call of CreateExportDir.
func (mr *MockWorkspaceOpsMockRecorder) CreateExportDir() *MockWorkspaceOpsCreateExportDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExportDir", reflect.TypeOf((*MockWorkspaceOps)(nil).CreateExportDir))
	return &MockWorkspaceOpsCreateExportDirCall{Call: call}
}

// MockWorkspaceOpsCreateExportDirCall wrap *gomock.Call
type MockWorkspaceOpsCreateExportDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsCreateExportDirCall) Return(arg0 string, arg1 error) *MockWorkspaceOpsCreateExportDirCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsCreateExportDirCall) Do(f func() (string, error)) *MockWorkspaceOpsCreateExportDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsCreateExportDirCall) DoAndReturn(f func() (string, error)) *MockWorkspaceOpsCreateExportDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DownloadSpec mocks base method.
func (m *MockWorkspaceOps) DownloadSpec(ctx context.Context, location string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadSpec", ctx, location)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadSpec indicates an expected call of DownloadSpec.
func (mr *MockWorkspaceOpsMockRecorder) DownloadSpec(ctx, location any) *MockWorkspaceOpsDownloadSpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadSpec", reflect.TypeOf((*MockWorkspaceOps)(nil).DownloadSpec), ctx, location)
	return &MockWorkspaceOpsDownloadSpecCall{Call: call}
}

// MockWorkspaceOpsDownloadSpecCall wrap *gomock.Call
type MockWorkspaceOpsDownloadSpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsDownloadSpecCall) Return(arg0 []byte, arg1 error) *MockWorkspaceOpsDownloadSpecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsDownloadSpecCall) Do(f func(context.Context, string) ([]byte, error)) *MockWorkspaceOpsDownloadSpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsDownloadSpecCall) DoAndReturn(f func(context.Context, string) ([]byte, error)) *MockWorkspaceOpsDownloadSpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Init mocks base method.
func (m *MockWorkspaceOps) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockWorkspaceOpsMockRecorder) Init() *MockWorkspaceOpsInitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockWorkspaceOps)(nil).Init))
	return &MockWorkspaceOpsInitCall{Call: call}
}

// MockWorkspaceOpsInitCall wrap *gomock.Call
type MockWorkspaceOpsInitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsInitCall) Return(arg0 error) *MockWorkspaceOpsInitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsInitCall) Do(f func() error) *MockWorkspaceOpsInitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsInitCall) DoAndReturn(f func() error) *MockWorkspaceOpsInitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSpecs mocks base method.
func (m *MockWorkspaceOps) ListSpecs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpecs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpecs indicates an expected call of ListSpecs.
func (mr *MockWorkspaceOpsMockRecorder) ListSpecs() *MockWorkspaceOpsListSpecsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpecs", reflect.TypeOf((*MockWorkspaceOps)(nil).ListSpecs))
	return &MockWorkspaceOpsListSpecsCall{Call: call}
}

// MockWorkspaceOpsListSpecsCall wrap *gomock.Call
type MockWorkspaceOpsListSpecsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsListSpecsCall) Return(arg0 []string, arg1 error) *MockWorkspaceOpsListSpecsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsListSpecsCall) Do(f func() ([]string, error)) *MockWorkspaceOpsListSpecsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsListSpecsCall) DoAndReturn(f func() ([]string, error)) *MockWorkspaceOpsListSpecsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResponsesDir mocks base method.
func (m *MockWorkspaceOps) ResponsesDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponsesDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// ResponsesDir indicates an expected call of ResponsesDir.
func (mr *MockWorkspaceOpsMockRecorder) ResponsesDir() *MockWorkspaceOpsResponsesDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponsesDir", reflect.TypeOf((*MockWorkspaceOps)(nil).ResponsesDir))
	return &MockWorkspaceOpsResponsesDirCall{Call: call}
}

// MockWorkspaceOpsResponsesDirCall wrap *gomock.Call
type MockWorkspaceOpsResponsesDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsResponsesDirCall) Return(arg0 string) *MockWorkspaceOpsResponsesDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsResponsesDirCall) Do(f func() string) *MockWorkspaceOpsResponsesDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsResponsesDirCall) DoAndReturn(f func() string) *MockWorkspaceOpsResponsesDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Root mocks base method.
func (m *MockWorkspaceOps) Root() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Root")
	ret0, _ := ret[0].(string)
	return ret0
}

// Root indicates an expected call of Root.
func (mr *MockWorkspaceOpsMockRecorder) Root() *MockWorkspaceOpsRootCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Root", reflect.TypeOf((*MockWorkspaceOps)(nil).Root))
	return &MockWorkspaceOpsRootCall{Call: call}
}

// MockWorkspaceOpsRootCall wrap *gomock.Call
type MockWorkspaceOpsRootCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsRootCall) Return(arg0 string) *MockWorkspaceOpsRootCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsRootCall) Do(f func() string) *MockWorkspaceOpsRootCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsRootCall) DoAndReturn(f func() string) *MockWorkspaceOpsRootCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveSpec mocks base method.
func (m *MockWorkspaceOps) SaveSpec(name string, data []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSpec", name, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSpec indicates an expected call of SaveSpec.
func (mr *MockWorkspaceOpsMockRecorder) SaveSpec(name, data any) *MockWorkspaceOpsSaveSpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSpec", reflect.TypeOf((*MockWorkspaceOps)(nil).SaveSpec), name, data)
	return &MockWorkspaceOpsSaveSpecCall{Call: call}
}

// MockWorkspaceOpsSaveSpecCall wrap *gomock.Call
type MockWorkspaceOpsSaveSpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsSaveSpecCall) Return(arg0 string, arg1 error) *MockWorkspaceOpsSaveSpecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsSaveSpecCall) Do(f func(string, []byte) (string, error)) *MockWorkspaceOpsSaveSpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsSaveSpecCall) DoAndReturn(f func(string, []byte) (string, error)) *MockWorkspaceOpsSaveSpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SpecPath mocks base method.
func (m *MockWorkspaceOps) SpecPath(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpecPath", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// SpecPath indicates an expected call of SpecPath.
func (mr *MockWorkspaceOpsMockRecorder) SpecPath(name any) *MockWorkspaceOpsSpecPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpecPath", reflect.TypeOf((*MockWorkspaceOps)(nil).SpecPath), name)
	return &MockWorkspaceOpsSpecPathCall{Call: call}
}

// MockWorkspaceOpsSpecPathCall wrap *gomock.Call
type MockWorkspaceOpsSpecPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceOpsSpecPathCall) Return(arg0 string) *MockWorkspaceOpsSpecPathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceOpsSpecPathCall) Do(f func(string) string) *MockWorkspaceOpsSpecPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceOpsSpecPathCall) DoAndReturn(f func(string) string) *MockWorkspaceOpsSpecPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRequestValidator is a mock of RequestValidator interface.
type MockRequestValidator struct {
	ctrl     *gomock.Controller
	recorder *MockRequestValidatorMockRecorder
	isgomock struct{}
}

// MockRequestValidatorMockRecorder is the mock recorder for MockRequestValidator.
type MockRequestValidatorMockRecorder struct {
	mock *MockRequestValidator
}

// NewMockRequestValidator creates a new mock instance.
func NewMockRequestValidator(ctrl *gomock.Controller) *MockRequestValidator {
	mock := &MockRequestValidator{ctrl: ctrl}
	mock.recorder = &MockRequestValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestValidator) EXPECT() *MockRequestValidatorMockRecorder {
	return m.recorder
}

// Struct mocks base method.
func (m *MockRequestValidator) Struct(arg0 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Struct", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Struct indicates an expected call of Struct.
func (mr *MockRequestValidatorMockRecorder) Struct(arg0 any) *MockRequestValidatorStructCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Struct", reflect.TypeOf((*MockRequestValidator)(nil).Struct), arg0)
	return &MockRequestValidatorStructCall{Call: call}
}

// MockRequestValidatorStructCall wrap *gomock.Call
type MockRequestValidatorStructCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRequestValidatorStructCall) Return(arg0 error) *MockRequestValidatorStructCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRequestValidatorStructCall) Do(f func(any) error) *MockRequestValidatorStructCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRequestValidatorStructCall) DoAndReturn(f func(any) error) *MockRequestValidatorStructCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSnapshotStore is a mock of SnapshotStore interface.
type MockSnapshotStore struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotStoreMockRecorder
	isgomock struct{}
}

// MockSnapshotStoreMockRecorder is the mock recorder for MockSnapshotStore.
type MockSnapshotStoreMockRecorder struct {
	mock *MockSnapshotStore
}

// NewMockSnapshotStore creates a new mock instance.
func NewMockSnapshotStore(ctrl *gomock.Controller) *MockSnapshotStore {
	mock := &MockSnapshotStore{ctrl: ctrl}
	mock.recorder = &MockSnapshotStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotStore) EXPECT() *MockSnapshotStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockSnapshotStore) Load() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(any)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockSnapshotStoreMockRecorder) Load() *MockSnapshotStoreLoadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSnapshotStore)(nil).Load))
	return &MockSnapshotStoreLoadCall{Call: call}
}

// MockSnapshotStoreLoadCall wrap *gomock.Call
type MockSnapshotStoreLoadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotStoreLoadCall) Return(arg0 any) *MockSnapshotStoreLoadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotStoreLoadCall) Do(f func() any) *MockSnapshotStoreLoadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotStoreLoadCall) DoAndReturn(f func() any) *MockSnapshotStoreLoadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Store mocks base method.
func (m *MockSnapshotStore) Store(arg0 any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Store", arg0)
}

// Store indicates an expected call of Store.
func (mr *MockSnapshotStoreMockRecorder) Store(arg0 any) *MockSnapshotStoreStoreCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockSnapshotStore)(nil).Store), arg0)
	return &MockSnapshotStoreStoreCall{Call: call}
}

// MockSnapshotStoreStoreCall wrap *gomock.Call
type MockSnapshotStoreStoreCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotStoreStoreCall) Return() *MockSnapshotStoreStoreCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotStoreStoreCall) Do(f func(any)) *MockSnapshotStoreStoreCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotStoreStoreCall) DoAndReturn(f func(any)) *MockSnapshotStoreStoreCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *MockClockNowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
	return &MockClockNowCall{Call: call}
}

// MockClockNowCall wrap *gomock.Call
type MockClockNowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockNowCall) Return(arg0 time.Time) *MockClockNowCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockNowCall) Do(f func() time.Time) *MockClockNowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockNowCall) DoAndReturn(f func() time.Time) *MockClockNowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSettingsProvider is a mock of SettingsProvider interface.
type MockSettingsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsProviderMockRecorder
	isgomock struct{}
}

// MockSettingsProviderMockRecorder is the mock recorder for MockSettingsProvider.
type MockSettingsProviderMockRecorder struct {
	mock *MockSettingsProvider
}

// NewMockSettingsProvider creates a new mock instance.
func NewMockSettingsProvider(ctrl *gomock.Controller) *MockSettingsProvider {
	mock := &MockSettingsProvider{ctrl: ctrl}
	mock.recorder = &MockSettingsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsProvider) EXPECT() *MockSettingsProviderMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockSettingsProvider) Config() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockSettingsProviderMockRecorder) Config() *MockSettingsProviderConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockSettingsProvider)(nil).Config))
	return &MockSettingsProviderConfigCall{Call: call}
}

// MockSettingsProviderConfigCall wrap *gomock.Call
type MockSettingsProviderConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSettingsProviderConfigCall) Return(arg0 *config.Config) *MockSettingsProviderConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSettingsProviderConfigCall) Do(f func() *config.Config) *MockSettingsProviderConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSettingsProviderConfigCall) DoAndReturn(f func() *config.Config) *MockSettingsProviderConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HTTPClientConfig mocks base method.
func (m *MockSettingsProvider) HTTPClientConfig() httpclient.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPClientConfig")
	ret0, _ := ret[0].(httpclient.Config)
	return ret0
}

// HTTPClientConfig indicates an expected call of HTTPClientConfig.
func (mr *MockSettingsProviderMockRecorder) HTTPClientConfig() *MockSettingsProviderHTTPClientConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPClientConfig", reflect.TypeOf((*MockSettingsProvider)(nil).HTTPClientConfig))
	return &MockSettingsProviderHTTPClientConfigCall{Call: call}
}

// MockSettingsProviderHTTPClientConfigCall wrap *gomock.Call
type MockSettingsProviderHTTPClientConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSettingsProviderHTTPClientConfigCall) Return(arg0 httpclient.Config) *MockSettingsProviderHTTPClientConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSettingsProviderHTTPClientConfigCall) Do(f func() httpclient.Config) *MockSettingsProviderHTTPClientConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSettingsProviderHTTPClientConfigCall) DoAndReturn(f func() httpclient.Config) *MockSettingsProviderHTTPClientConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MaxResponseSize mocks base method.
func (m *MockSettingsProvider) MaxResponseSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxResponseSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxResponseSize indicates an expected call of MaxResponseSize.
func (mr *MockSettingsProviderMockRecorder) MaxResponseSize() *MockSettingsProviderMaxResponseSizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxResponseSize", reflect.TypeOf((*MockSettingsProvider)(nil).MaxResponseSize))
	return &MockSettingsProviderMaxResponseSizeCall{Call: call}
}

// MockSettingsProviderMaxResponseSizeCall wrap *gomock.Call
type MockSettingsProviderMaxResponseSizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSettingsProviderMaxResponseSizeCall) Return(arg0 int) *MockSettingsProviderMaxResponseSizeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSettingsProviderMaxResponseSizeCall) Do(f func() int) *MockSettingsProviderMaxResponseSizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSettingsProviderMaxResponseSizeCall) DoAndReturn(f func() int) *MockSettingsProviderMaxResponseSizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
