mock_enabled: true

specs:
  - domain: meteo
    base_url: https://meteo.swagger.io/v2
    llm_title: Open-Meteo API
    llm_instruction: |
      Use this API to manage pets, orders, and users.
      Mock server generates random data for all endpoints.
    tags:
      - demo
      - mock
    auth:
      type: bearer
      config:
        token: any-token
    collections:
      - llm_title: Open-Meteo Swagger
        location: https://raw.githubusercontent.com/mmadfox/swag2mcp/main/specs/meteo.json
        base_mock_url: localhost:8080
