mock_enabled: true

specs:
  - domain: petstore
    base_url: https://petstore.swagger.io/v2
    llm_title: Petstore API
    llm_instruction: |
      Use this API to manage pets, orders, and users.
      Mock server generates random data for all endpoints.
    tags:
      - demo
      - mock
    auth:
      type: bearer
      config:
        token: any-token
    collections:
      - llm_title: Petstore Swagger
        location: specs/petstore.json
        base_mock_url: localhost:8080
